### ISSUE TITLE
JsonBase.php: use JsonSerializable;

### ISSUE THREAD

**Issue by hgreuvers** [PayCheckout-BV/PayCheckoutApiPHP#1]
JsonSerializable supported from PHP 5 >= 5.4.0 instead of mentioned PHP 5 >= 5.3.0!

http://php.net/manual/en/jsonserializable.jsonserialize.php

**Comment by PayCheckout** [comment]
We will discuss this with the development team tomorrow, assuming you are right we will correct this as proposed. Thanks for informing us.

**Comment by PayCheckout** [comment]
Issue resolved, released new package, with updated requirement.
